services:

  caddy:
    image: caddy:${CADDY_TAG:-latest}
    command: caddy reverse-proxy --from ${JELLYFIN_PublishedServerUrl:?JELLYFIN_PublishedServerUrl required in env for caddy deploy} --to jellyfin:${JELLYFIN_PORT:-8096}
    restart: ${RESTART:-unless-stopped}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: