services:

  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_TAG:-latest}
    user: ${UID:-0}:${GID:-0}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
    volumes:
      - ${MEDIA_PATH:?MEDIA_PATH required in env}:/media
      - ${CONFIG_PATH:-config}:/config
      - ${CACHE_PATH:-cache}:/cache
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl:-}

volumes:
  config:
  cache: